# Generated by Django 5.1.2 on 2025-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_anonymousorder_assigned_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='books_given_free',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='books_sold_money',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='books_given_free_details',
            field=models.JSONField(default=list, help_text='List of books given free with quantities'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='books_sold_details',
            field=models.JSONField(default=list, help_text='List of books sold with quantities'),
        ),
    ]
