# Generated by Django 5.1.2 on 2025-08-05 13:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold_money', models.PositiveIntegerField(default=0, help_text='Books sold for money')),
                ('quantity_given_free', models.PositiveIntegerField(default=0, help_text='Books given for free')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per book sold', max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue from this book', max_digits=10)),
                ('date_reported', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reported', '-created_at'],
                'unique_together': {('seller', 'product', 'date_reported')},
            },
        ),
    ]
